name: analyzer

on:
  pull_request:

jobs:
  gcc-analyzer:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install GCC toolchain
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi cmake ninja-build

      - name: Configure (GCC static analyzer)
        run: |
          set -e
          cmake -S bms -B build-analyzer \
            -DCMAKE_TOOLCHAIN_FILE=cmake/gcc-arm-none-eabi.cmake \
            -DCMAKE_C_FLAGS="\
              -fanalyzer \
              -Wall -Wextra -Wpedantic \
              -Werror \
              -Wshadow \
              -Wundef \
              -Wformat=2 \
              -Wdouble-promotion \
              -fno-common \
            " \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build (analysis only)
        run: |
          set -e
          cmake --build build-analyzer
